
    create table tb_user (
       id int8 generated by default as identity,
        cep varchar(255),
        email varchar(255),
        login varchar(255),
        nome varchar(255),
        password varchar(255),
        primary key (id)
    );

    alter table if exists tb_user 
       add constraint UK_qht682qvopcx5f41dc2rbs5jf unique (login);
